### ISSUE TITLE
Github Organization Request

### ISSUE THREAD

**Issue by f3r** [XMansion/Scrooge#1]
Hi there Anunay! I started a new project called XMansion and I noticed you created an organization time ago for your personal projects called also XMansion (https://github.com/xmansion).

If you are not using it anymore, would it be possible to free the name? I would appreciate it a lot!! <3 Thank you so much and have a wonderful day sir :)

/Fer

**Comment by Anunay-Sinha** [comment]
I intend to use it, but if you needs more than mine I will rename it by tomorrow morning. Its warning me of certain bad things, so will do that once am back home . You can check back in 24 hours, you may find it available

**Comment by f3r** [comment]
Thanks so much Anunay!! You are so kind! I bought the domain (xmansion) last week and I intend to launch a coding school for *gifted youngsters* in my community here. I truly appreciate your kindness. Could you let me know here when you free it?

God bless you

**Comment by Anunay-Sinha** [comment]
I am doing it now. you should be good to go

**Comment by Anunay-Sinha** [comment]
Done. 
wish you luck with your project.

**Comment by f3r** [comment]
Thank you!!  Will try my best!

![](https://media2.giphy.com/media/l2R0eYcNq9rJUsVAA/giphy.gif)
